export const SET_GAME_STARTED='SET_GAME_STARTED'
export const SET_INSTRAUCTIONS_EXPANDED='SET_INSTRAUCTIONS_EXPANDED'

export const DECK ={
    FETCH_SUCCESS:'DECK_FETCH_SUCCES',
    FETCH_ERROR:'DECK_FETCH_ERROR'
}
